name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore ./MyConsoleApp/MyGitHubActionsSolution.sln
            
    - name: Build
      run: dotnet build ./MyConsoleApp/MyGitHubActionsSolution.sln --configuration Release --no-restore
            
    - name: Test
      run: dotnet test ./MyConsoleApp/MyGitHubActionsSolution.sln --no-restore --verbosity normal
            
    - name: Publish
      run: dotnet publish ./MyConsoleApp/MyGitHubActionsSolution.sln -c Release -o dotnetcorewebapp
            
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: "./dotnetcorewebapp"
